---
# TODO
# Change dev address
dev_addr: "0.0.0.0:8002"
site_name: "pynautobot Docs"
copyright: "Copyright &copy; The Authors"
theme:
  name: "material"
  navigation_depth: 4
  # custom_dir: "docs/assets/overrides"
  hljs_languages:
    - "django"
    - "yaml"
  features:
    - "content.code.copy"
    - "navigation.footer"
    - "navigation.tabs"
    - "navigation.tabs.sticky"
    - "navigation.tracking"
    - "search.highlight"
    - "search.share"
    - "search.suggest"
  favicon: "assets/favicon.ico"
  logo: "assets/nautobot_logo.svg"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: "default"
      primary: "black"
      toggle:
        icon: "material/weather-sunny"
        name: "Switch to dark mode"

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: "slate"
      primary: "black"
      toggle:
        icon: "material/weather-night"
        name: "Switch to light mode"

# The animated *.gif files in nautobot/docs/media are only used in the README.
# Since their file size is quite large, we exclude them from the built docs.
exclude_docs: |
  /media/*.gif

validation:
  absolute_links: warn
  omitted_files: warn
  unrecognized_links: warn

extra_css:
  - "assets/extra.css"

# needed for RTD version flyout menu
# jquery is not (yet) injected by RTD automatically and it might be dropped
# as a dependency in the future
extra_javascript:
  - "https://code.jquery.com/jquery-3.7.1.min.js"

extra:
  generator: false
  ntc_sponsor: true
  social:
    - icon: "fontawesome/solid/rss"
      link: "https://blog.networktocode.com/blog/tags/nautobot"
      name: "Network to Code Blog"
    - icon: "fontawesome/brands/youtube"
      link: "https://www.youtube.com/playlist?list=PLjA0bhxgryJ2Ts4GJMDA-tPzVWEncv4pb"
      name: "Nautobot Videos"
    - icon: "fontawesome/brands/slack"
      link: "https://www.networktocode.com/community/"
      name: "Network to Code Community"
    - icon: "fontawesome/brands/github"
      link: "https://github.com/nautobot/nautobot"
      name: "GitHub Repo"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/networktocode"
      name: "Network to Code Twitter"
markdown_extensions:
  - "admonition"
  - "toc":
      permalink: true
  - "attr_list"
  - "markdown_data_tables":
      base_path: "docs"
  - "md_in_html"
  - "pymdownx.details"
  - "pymdownx.highlight":
      anchor_linenums: true
  - "pymdownx.inlinehilite"
  - "pymdownx.snippets"
  - "pymdownx.superfences":
      custom_fences:
        - name: "mermaid"
          class: "mermaid"
          format: !!python/name:pymdownx.superfences.fence_code_format
  - "pymdownx.tabbed":
      "alternate_style": true

nav:
  - Overview: "index.md"
  - Adminsitrator Guide:
      - Install and Configure: "admin/install.md"
      - Upgrade: "admin/upgrade.md"
      - Uninstall: "admin/uninstall.md"
      - Release Notes:
          - "admin/release_notes/index.md"
plugins:
  - "search"
  - "mkdocstrings":
      default_handler: "python"
      handlers:
        python:
          paths: ["."]
          options:
            heading_level: 1
            show_root_heading: true
            show_root_members_full_path: true
            show_source: false
